### ISSUE TITLE
Aggressive Cows Problem

### ISSUE THREAD

**Issue by tanishgoyal07** [Rj-coder-iitian/FAANG-Leetcode-questions#141]
I want  to add aggressive cows problem

**Comment by tanishgoyal07** [comment]
@Rj-coder-iitian please assign this task to me

**Comment by iamrishabhjoshi** [comment]
@Rj-coder-iitian Please assign this issue to me.

**Comment by Rj-coder-iitian** [comment]
As @iamrishabhjoshi asked first, I have assigned this to him.
